version: "3.8"
services:
  db_auth:
    image: postgres:10.1
    container_name: auth-db
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5431:5432
  db_booking:
    image: postgres:10.1
    container_name: boking-db
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
  db_devices:
    image: postgres:10.1
    container_name: device-db
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5433:5432
  zookeeper:
    image: 'bitnami/zookeeper:3.7'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper