server:
  port: 8080
spring:
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  r2dbc:
    username: postgres
    password: postgres
    url: r2dbc:postgresql://localhost:5431/postgres
    pool.enabled: true
    pool.initial-size: 10
    pool.max-idle-time: 1m
    pool.max-size: 30
  data:
    r2dbc:
      repositories:
        enabled: true